<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SeedRolesFr extends Seeder
{
    public function run()
    {
        DB::table('roles')->insert([
            // Rôles centraux
            [
                'name' => 'Président Directeur Général',
                'name_ar' => 'الرئيس المدير العام',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Directeur Central',
                'name_ar' => 'مدير مركزي',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Rôles liés aux centres
            [
                'name' => 'Directeur de centre de formation professionnelle',
                'name_ar' => 'مدير مركز تكوين مهني',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Assistant de direction',
                'name_ar' => 'مساعد مديرية',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chauffeur',
                'name_ar' => 'سائق',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chargé d\'information, d\'orientation et d\'accompagnement',
                'name_ar' => 'المكلّف بالإعلام والتوجيه والمرفقة',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Coordinateur technique',
                'name_ar' => 'منسق الفني',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chargé de la gestion des affaires des stagiaires',
                'name_ar' => 'المكلّف بالتصرف في شؤون المتكونين',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Surveillant de jour',
                'name_ar' => 'قيم بالنهار',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chargé du suivi de la formation',
                'name_ar' => 'المكلّف بمتابعة التقييم',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chargé du développement',
                'name_ar' => 'المكلّف بالتطوير',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chargé des stages et de la restauration',
                'name_ar' => 'المكلّف بشؤون المبيت المطعم',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cuisinier',
                'name_ar' => 'طبّاخ',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aide-cuisinier',
                'name_ar' => 'مساعد طبّاخ',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Surveillant de nuit',
                'name_ar' => 'قيم بالليل',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Animateur de la vie sociale',
                'name_ar' => 'المكلّف بتنشيط الحياة الجماعية',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Responsable administratif et financier',
                'name_ar' => 'المكلّف بالتصرف الإداري والمالي',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Magasinier',
                'name_ar' => 'حافظ المغازة',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ordonnateur des dépenses',
                'name_ar' => 'مفوض الميزانية',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Comptable',
                'name_ar' => 'محتسب',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chargé de maintenance et logistique',
                'name_ar' => 'المكلّف بالصيانة واللوجستيك',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Économe',
                'name_ar' => 'مقتصد',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Formateur',
                'name_ar' => 'مكون',
                'guard_name' => 'web',
                'statut' => 'Actif',
                'creer_par' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
